

services:
  # 基础设置
  postgres:
    image: postgres:16        # 指定具体版本
    container_name: the_pass_postgres
    restart: unless-stopped
    environment: # 环境变量
      POSTGRES_USER: the_pass     # 数据库用户名
      POSTGRES_PASSWORD: the_pass # 数据库密码
      POSTGRES_DB: the_pass_db    # 默认数据库名
      TZ: Asia/Shanghai           # 设置时区
    # 端口映射
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # 数据卷挂载
    healthcheck:  # 健康检查
      test: ["CMD", "pg_isready", "-U", "the_pass"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "max_connections=200"] # 设置最大连接数为 200  # 自定义配置

volumes:
  pgdata: # 定义一个命名卷用于数据持久化
