# 后端服务端口
server:
  port: 13544
  # 添加CORS配置
  cors:
    allowed_origins:
      - "http://localhost:5173"   # Vite默认端口
      - "http://localhost:3000"   # 备用前端端口
      - "http://localhost:4173"   # Vite预览模式
      - "https://app.yourcompany.com"  # 生产环境
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"

# 数据库配置
database:
  host: "localhost"
  port: 5432
  username: "the_pass"
  password: "the_pass"
  db_name: "the_pass_db"

# JWT配置
jwt:
  secret_key: "3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s"
  expires_in: 43200 # 12小时 (12 * 60 * 60)

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""       # 如果Redis有密码就填写，没有留空
  database: 0        # 使用Redis的第0个数据库
  pool_size: 10      # 连接池大小
  min_idle_conns: 5  # 最小空闲连接数
